// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WindroseLogs.Infrastructure.Data;

#nullable disable

namespace WindroseLogs.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260330140043_AddBotWatchedChats")]
    partial class AddBotWatchedChats
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WindroseLogs.Core.Models.BotWatchedChat", b =>
                {
                    b.Property<string>("ChatId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("BotId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsChannel")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("LastCheck")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("RegisteredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ServiceUrl")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("ChatId");

                    b.ToTable("BotWatchedChats");
                });

            modelBuilder.Entity("WindroseLogs.Core.Models.EventSignature", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConditionText")
                        .HasColumnType("text");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("FileCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("FirstSeen")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("LastSeen")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SignatureHash")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("SourceFile")
                        .HasColumnType("text");

                    b.Property<int>("TotalCount")
                        .HasColumnType("integer");

                    b.Property<string>("WhereText")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SignatureHash")
                        .IsUnique();

                    b.HasIndex("EventType", "TotalCount");

                    b.ToTable("EventSignatures");
                });

            modelBuilder.Entity("WindroseLogs.Core.Models.LogEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.PrimitiveCollection<List<string>>("Callstack")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("CheckCondition")
                        .HasColumnType("text");

                    b.Property<string>("CheckMessage")
                        .HasColumnType("text");

                    b.Property<string>("CheckSourceFile")
                        .HasColumnType("text");

                    b.Property<string>("CheckWhere")
                        .HasColumnType("text");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Dictionary<string, string>>("Extra")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Guid>("FileId")
                        .HasColumnType("uuid");

                    b.Property<int>("FrameNumber")
                        .HasColumnType("integer");

                    b.Property<double?>("MemoryGrowthRate")
                        .HasColumnType("double precision");

                    b.Property<string>("MemoryWorld")
                        .HasColumnType("text");

                    b.Property<Guid>("SignatureId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SignatureId");

                    b.HasIndex("Timestamp");

                    b.HasIndex("FileId", "EventType");

                    b.ToTable("LogEvents");
                });

            modelBuilder.Entity("WindroseLogs.Core.Models.LogFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<int>("EventsFound")
                        .HasColumnType("integer");

                    b.Property<string>("FileHash")
                        .HasColumnType("text");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateOnly?>("SessionDate")
                        .HasColumnType("date");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("TotalLines")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UploadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UploadedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("UploaderName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.HasIndex("UploadedAt");

                    b.HasIndex("UploadedBy");

                    b.ToTable("LogFiles");
                });

            modelBuilder.Entity("WindroseLogs.Core.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("WindroseLogs.Core.Models.LogEvent", b =>
                {
                    b.HasOne("WindroseLogs.Core.Models.LogFile", "File")
                        .WithMany("Events")
                        .HasForeignKey("FileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WindroseLogs.Core.Models.EventSignature", "Signature")
                        .WithMany("Events")
                        .HasForeignKey("SignatureId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("File");

                    b.Navigation("Signature");
                });

            modelBuilder.Entity("WindroseLogs.Core.Models.LogFile", b =>
                {
                    b.HasOne("WindroseLogs.Core.Models.User", "Uploader")
                        .WithMany("UploadedFiles")
                        .HasForeignKey("UploadedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Uploader");
                });

            modelBuilder.Entity("WindroseLogs.Core.Models.EventSignature", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("WindroseLogs.Core.Models.LogFile", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("WindroseLogs.Core.Models.User", b =>
                {
                    b.Navigation("UploadedFiles");
                });
#pragma warning restore 612, 618
        }
    }
}
